services:
  youtubedl:
    build: .
    container_name: youtubedl
    networks:
      - web
    ports:
      - "8000:8000"
    restart: unless-stopped

networks:
  web:
    external: true
    name: web
